# This is the API definition that acts as the template for go-swagger to auto-generate
# boilerplate go code. 
# For a simple todo-list server tutorial that explains the swagger definitions, see:
# https://goswagger.io/tutorial/todo-list.html
# For go-swagger developer instructions and a description of the structure of the `api` directory,
# see the `README.md` for this project.
#
# The two categories of API definitions that impact the manually written segments of the backend:
# - paths:        Defines the URL paths accessible by the API, including parameters and responses.
#                 These are used to to populate the `operations` package (found in
#                 `restapi/operations`), and a handler (to be manually implemented) is generated
#                 for each of these in `configure_variant_service.go`
# - definitions:  Defines the schemas/models in the API, for parameters and for responses, to be
#                 represented by go structs in the code.
#                 These are used to to populate the `models` package and can be referred to
#                 throughout this `swagger.yml` file to describe a `schema` property.

consumes:
- application/json
info:
  description: A model variant service demonstarting CanDIG API best practices
  title: A barebones service for variant calls
  version: 1.0.0
produces:
- application/json
schemes:
- http
swagger: "2.0" # version used by go-swagger tool

paths:
  /individuals:
    post:
      operationId: post_individual
      summary: Add an individual to the database
      parameters:
      - name: individual
        in: body
        schema:
          $ref: '#/definitions/Individual'
      responses:
        201:
          description: New individual created
          schema:
            $ref: "#/definitions/Individual"
          headers:
            Location:
              type: string
              format: url
        405:
          description: Forbidden to overwrite individual in post
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal error - Individual not created
          schema:
            $ref: "#/definitions/Error"
    get:
      operationId: get_individuals
      summary: Get all individuals
      responses:
        200:
          description: Return individuals
          schema:
            type: array
            items:
              $ref: '#/definitions/Individual'
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /individuals/{individual_id}:
    get:
      operationId: get_one_individual
      summary: Get specific individual
      parameters:
      - $ref: '#/parameters/individual_id'
      responses:
        200:
          description: Return individual
          schema:
            $ref: '#/definitions/Individual'
        404:
          description: Individual not found
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /variants:
    get:
      operationId: get_variants
      summary: Get all variants within genomic range
      parameters:
        - name: chromosome
          in: query
          type: string
          pattern: "^[a-zA-Z0-9]*$"
        - name: start
          in: query
          type: integer
          minimum: 1
        - name: end
          in: query
          type: integer
          minimum: 1
      responses:
        200:
          description: Return variants
          schema:
            type: array
            items:
              $ref: '#/definitions/Variant'
        403:
          description: Forbidden to query for all variants
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"
    post:
      operationId: post_variant
      summary: Add a variant to the database
      parameters:
        - name: variant
          in: body
          schema:
            $ref: '#/definitions/Variant'
      responses:
        201:
          description: New variant created
          schema:
            $ref: "#/definitions/Variant"
          headers:
            Location:
              type: string
              format: url
        400:
          description: Variant provided in body does not pass schema validation
          schema:
            $ref: "#/definitions/Error"
        405:
          description: Forbidden to overwrite variant in put
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal error - Variant not created
          schema:
            $ref: "#/definitions/Error"

  /variants/{variant_id}:
    get:
      operationId: get_one_variant
      summary: Get specific variant
      parameters:
        - $ref: '#/parameters/variant_id'
      responses:
        200:
          description: Return variant
          schema:
            $ref: '#/definitions/Variant'
        404:
          description: Variant not found
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /calls:
    post:
      operationId: post_call
      summary: Add a call to the database
      parameters:
        - name: call
          in: body
          schema:
            $ref: '#/definitions/Call'
      responses:
        201:
          description: New call created
          schema:
            $ref: "#/definitions/Call"
          headers:
            Location:
              type: string
              format: url
        405:
          description: Cannot overwrite call
          schema:
            $ref: "#/definitions/Error"
    get:
      operationId: get_calls
      summary: Get all calls
      responses:
        200:
          description: Return calls
          schema:
            type: array
            items:
              $ref: '#/definitions/Call'

  /calls/{call_id}:
    get:
      operationId: get_one_call
      summary: Get specific call
      parameters:
        - $ref: '#/parameters/call_id'
      responses:
        200:
          description: Return call
          schema:
            $ref: '#/definitions/Call'
        404:
          description: Call not found
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /individuals/{individual_id}/variants:
    get:
      operationId: get_variants_by_individual
      summary: Get variants called in an individual
      parameters:
        - $ref: '#/parameters/individual_id'
      responses:
        200:
          description: Return individuals
          schema:
            type: array
            items:
              $ref: '#/definitions/Variant'
        404:
          description: Individual does not exist
          schema:
            $ref: "#/definitions/Error"

  /variants/{variant_id}/individuals:
    get:
      operationId: get_individuals_by_variant
      summary: Get individuals with a given variant called
      parameters:
        - $ref: '#/parameters/variant_id'
      responses:
        200:
          description: Return individuals
          schema:
            type: array
            items:
              $ref: '#/definitions/Individual'
        404:
          description: Variant does not exist
          schema:
            $ref: "#/definitions/Error"

parameters:
  variant_id:
    name: variant_id
    description: Variant unique identifier
    in: path
    type: string
    format: uuid
    x-example: bf3ba75b-8dfe-4619-b832-31c4a087a589
    required: true

  individual_id:
    name: individual_id
    description: Individual unique identifier
    in: path
    type: string
    format: uuid
    x-example: bf3ba75b-8dfe-4619-b832-31c4a087a589
    required: true

  call_id:
    name: call_id
    description: Call unique identifier
    in: path
    type: string
    format: uuid
    x-example: bf3ba75b-8dfe-4619-b832-31c4a087a589
    required: true

definitions:
  Error:
    type: object
    required:
      - message
    properties: 
      code:
        type: integer
        format: int32
      message:
        type: string
  Individual:
    type: object
    required:
      - description
    properties:
      id:
        type: string
        format: uuid
        description: Unique internal identifier
        # TODO should we be scarmbling this uuid 
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2017-07-21T17:32:28Z"
        readOnly: true
      description:
        type: string
        description: Description of subject (may be external identifier)
        example: "Subject 17"
        minLength: 1
        maxLength: 100
  Call:
    type: object
    required:
      - individual_id
      - variant_id
      - genotype
    properties:
      id:
        type: string
        format: uuid
        description: Unique internal identifier
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2017-07-21T17:32:28Z"
        readOnly: true
      individual_id:
        type: integer
        format: int64
        description: Unique internal identifier for the subject
        example: 123
      variant_id:
        type: integer
        format: int64
        description: Unique internal identifier for the variant
        example: 123
      genotype:
        type: string
        description: Called genotype
        example: "0/1"
      format:
        type: string
        description: Additional call information
        example: "GQ:DP:HQ 48:1:51,51"
        minLength: 0
        maxLength: 100
        default: ""
  Variant:
    type: object
    required:
      - chromosome
      - start
      - ref
      - alt
    properties:
      id:
        type: string
        format: uuid
        description: Unique internal identifier
        example: bf3ba75b-8dfe-4619-b832-31c4a087a589
        readOnly: true
      name:
        type: string
        description: Variant name, if any
        example: "rs6054257"
        minLength: 0
        maxLength: 100
        default: ""
      chromosome:
        type: string
        description: Chromosome that the variant occurs on
        example: "chr1"
        minLength: 1
        maxLength: 10
      start:
        type: integer
        description: Beginning location of variant
        example: 14370
        minimum: 1
      ref:
        type: string
        description: Reference bases
        example: "G"
      alt:
        type: string
        description: Alternate (variant) bases
        example: "A"
        